apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-simple-gvisor.fullname" . }}
  labels:
    {{- include "my-simple-gvisor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-simple-gvisor.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-simple-gvisor.labels" . | nindent 8 }}
    spec:
      {{- if .Values.runtimeClassName }}
      runtimeClassName: {{ .Values.runtimeClassName }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.tmpVolume.enabled }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          {{- end }}
      {{- if .Values.tmpVolume.enabled }}
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: {{ .Values.tmpVolume.sizeLimit }}
      {{- end }}