apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-simple-gvisor.fullname" . }}
  labels:
    {{- include "my-simple-gvisor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-simple-gvisor.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-simple-gvisor.labels" . | nindent 8 }}
    spec:
      {{- if .Values.runtimeClassName }}
      runtimeClassName: {{ .Values.runtimeClassName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}