apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-simple-gvisor.fullname" . }}
  labels:
    {{- include "my-simple-gvisor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "my-simple-gvisor.labels" . | nindent 4 }}